# Generated by Django 3.2 on 2021-05-02 08:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('pmid', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('abstract', models.TextField()),
                ('pub_year', models.IntegerField()),
                ('source', models.CharField(max_length=200)),
                ('authors', models.CharField(max_length=200)),
                ('pubtype', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CommonTreatmentAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('annotator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ContextualEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DemographicEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtype', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecommendationAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_recommended', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('annotator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='s_annotator', to=settings.AUTH_USER_MODEL)),
                ('contextual_entities', models.ManyToManyField(related_name='s_contexts', to='labeling.ContextualEntity')),
                ('demographic_entities', models.ManyToManyField(related_name='s_demographics', to='labeling.DemographicEntity')),
                ('primary_condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labeling.condition')),
            ],
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubpopulationSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('associated_annotations', models.ManyToManyField(related_name='s_annotations', to='labeling.RecommendationAnnotation')),
                ('primary_condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labeling.condition')),
                ('summarizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='recommendationannotation',
            name='treatment_entities',
            field=models.ManyToManyField(related_name='s_treatments', to='labeling.Treatment'),
        ),
        migrations.AddField(
            model_name='recommendationannotation',
            name='verifiers',
            field=models.ManyToManyField(related_name='s_verifiers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='GeneralPopulationSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('associated_annotations', models.ManyToManyField(related_name='g_annotations', to='labeling.CommonTreatmentAnnotation')),
                ('primary_condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labeling.condition')),
                ('summarizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ConditionMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('article_pool', models.ManyToManyField(related_name='pool', to='labeling.Article')),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labeling.condition')),
                ('contributors', models.ManyToManyField(related_name='cm_contributors', to=settings.AUTH_USER_MODEL)),
                ('marked_irrelevant', models.ManyToManyField(related_name='cm_irrelevant', to='labeling.Article')),
                ('marked_relevant', models.ManyToManyField(related_name='cm_relevant', to='labeling.Article')),
            ],
        ),
        migrations.AddField(
            model_name='commontreatmentannotation',
            name='condition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labeling.condition'),
        ),
        migrations.AddField(
            model_name='commontreatmentannotation',
            name='treatments',
            field=models.ManyToManyField(related_name='g_treatments', to='labeling.Treatment'),
        ),
        migrations.AddField(
            model_name='commontreatmentannotation',
            name='verifiers',
            field=models.ManyToManyField(related_name='g_verifiers', to=settings.AUTH_USER_MODEL),
        ),
    ]
